name: OneDrive Sync
slug: onedrive_sync
version: "1.1.1"
description: Mirror a local folder ↔ a OneDrive folder using abraunegg/onedrive v2.5.5
url: https://github.com/your-repo/addons/local/onedrive_sync
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto

# namapovat hostitelské /media
map:
  - media:rw

options:
  local_folder: "/media/onedrive/"
  remote_folder: "HomeAssistant"
  application_id: ""
  azure_tenant_id: "common"
  onedrive_authresponse: ""
  monitor_interval: 300            # polling interval in seconds (default 300)
  monitor_fullscan_frequency: 12   # full-scan every N intervals (default 12)

schema:
  local_folder: str
  remote_folder: str?
  application_id: str?
  azure_tenant_id: str?
  onedrive_authresponse: str?
  monitor_interval: int?
  monitor_fullscan_frequency: int?
